# Generated by Django 5.1.1 on 2024-10-07 00:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('student', 'Estudiante'), ('tutor', 'Tutor')], default='student', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('students', models.ManyToManyField(related_name='student_groups', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutored_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_in_bank', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accounts_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('inventory', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('computer_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('furniture_fixtures', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('machinery_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('patents', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accounts_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('long_term_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retained_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projected_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operating_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='app_ceo.group')),
            ],
            options={
                'verbose_name': 'Dato Financiero',
                'verbose_name_plural': 'Datos Financieros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='app_ceo.financialdata')),
            ],
            options={
                'verbose_name': 'Inventario de Materia Prima',
                'verbose_name_plural': 'Inventario de Materia Prima',
                'ordering': ['-created_at'],
            },
        ),
    ]
