# Generated by Django 5.1.1 on 2024-10-04 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ceo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Financial Data', 'verbose_name_plural': 'Financial Data'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialinventory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Raw Material Inventory', 'verbose_name_plural': 'Raw Material Inventories'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='financial_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='app_ceo.financialdata'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
    ]
