# Generated by Django 5.1.1 on 2024-10-04 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ceo', '0002_alter_financialdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dato Financiero', 'verbose_name_plural': 'Datos Financieros'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterialinventory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventario de Materia Prima', 'verbose_name_plural': 'Inventarios de Materias Primas'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Por favor, introduce una dirección de correo válida.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('tutor', 'Tutor')], default='student', max_length=10),
        ),
    ]
